- hosts: example.ru

  remote_user: deployer
  become: yes
  become_method: sudo
  tasks:
  - name: Ansible copy file force
    copy:
      src: ~/Develop/permutations.py
      dest: /etc/cert/permutations.py
