- hosts: example.ru
  tasks:
    - name: Define your private or public registry
      docker_login:
        registry: macbookpro02.open.ru
        #username: name
        #password: SECRET
        #email: secret@gmail.com
        #reauth: yes
    - name: pull an image
      docker_image:
        name: localhost:5000/redshift_django
#    - name: Create a data container
#      docker_container:
#        name: name
#        image: vivekyad4v/local-simple-python
